libapp/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^about$', views.about, name='about'),
        url(r'^detail/(?P<item_id>\d+)/$', views.detail, name='detail'),
        url(r'^newitem$',views.newitem,name='newitem'),
        url(r'^suggestions$',views.suggestions,name='suggestions'),
        url(r'^search$',views.searchlib,name='search'),
        url(r'^login$',views.user_login,name='login'),
        url(r'^register$',views.register,name='register'),
        url(r'^logout$',views.user_logout,name='logout'),
        url(r'^myitems$',views.myitems,name='myitems'),
        url(r'^info/(?P<item_id>\d+)/$',views.info,name='info')
<<<<<<< HEAD

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
=======
        ]

>>>>>>> 239430217a857472dac71278789be7b15a676cfe

libsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^libapp/', include('libapp.urls', namespace = 'libapp'))
]

libapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

# Create your models here.

class LibUser(User):
    PROVINCE_CHOICES = (
        ('AB','Alberta'),
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'),

    )
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    phone = models.IntegerField(null=True)
    postalcode = models.CharField(null=True,blank=True,max_length=7)
    upload = models.FileField(null=True,blank=True,upload_to='uploads/%Y/%m/%d/')

class Libitem(models.Model):
    TYPE_CHOICES = (
        ('Book', 'Book'),
        ('DVD','DVD'),
        ('Other', 'Other'),
    )
    title = models.CharField(max_length=100)
    itemtype = models.CharField(max_length=6, choices=TYPE_CHOICES, default='Book')
    checked_out=models.BooleanField(default=False)
    user=models.ForeignKey(LibUser, default=None, null=True, blank=True)
    duedate=models.DateField(default=None, null=True, blank=True)
    last_chkout = models.DateField(default=None, null=True, blank=True)
    date_acquired = models.DateField(default=datetime.date.today())
    pubyr = models.IntegerField()
    num_chkout = models.IntegerField(blank=False,default=0)

    def overdue(self):
        if self.checked_out == True and self.duedate < datetime.date.today():
            return 'Yes'
    overdue.short_description = 'Overdue'




class Book(Libitem):
    CATEGORY_CHOICES = (
        (1, 'Fiction'),
        (2, 'Biography'),
        (3, 'Self Help'),
        (4, 'Education'),
        (5, 'Children'),
        (6, 'Teen'),
        (7, 'Other'),
    )
    author = models.CharField(max_length=100)
    category = models.IntegerField(choices=CATEGORY_CHOICES, default=1)

    def __str__(self):
        return self.title + ' by ' + self.author

class Dvd(Libitem):
    maker = models.CharField(max_length=100)
    duration = models.IntegerField()
    rating_choices = (
        (1,'G'),
        (2,'PG'),
        (3,'PG-13'),
        (4,'14A'),
        (5,'R'),
        (6,'NR'),
    )
    rating = models.IntegerField(choices=rating_choices,default=1)

    def __str__(self):
        return self.title + ' by ' + self.maker

class Suggestion(models.Model):

    TYPE_CHOICES = (
        (1, 'Book'),
        (2,'DVD'),
        (3, 'Other'),
    )
    title = models.CharField(max_length=100)
    pubyr = models.IntegerField(null=True, blank=True)
    type = models.IntegerField(default=1, choices=TYPE_CHOICES)
    cost = models.IntegerField()
    num_interested = models.IntegerField()
    comments = models.TextField(blank=True)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    picture = models.ImageField(upload_to='profile_images',blank=True)

    def __str__(self):
        return self.user.username

libapp/forms.py
from django import forms

from libapp.models import Suggestion,User,UserProfile

from libapp.models import Suggestion,User,LibUser

from libapp.validators import validate_pubyr

class SuggestionForm(forms.ModelForm):
    class Meta:
        model= Suggestion
        fields=['title','pubyr','type','cost','comments']
    choice = [('2','Dvd'),('1','Book')]
    title = forms.CharField(label='Title',max_length=100,widget=forms.TextInput(attrs={'class': "form-control"}))
    pubyr = forms.IntegerField(label='Publication Year',validators=[validate_pubyr],widget=forms.TextInput(attrs={'class': "form-control"}))
    type = forms.ChoiceField(label='Type',choices = choice,widget=forms.RadioSelect())
    cost = forms.IntegerField(label='Estimated Cost in Dollars',widget=forms.TextInput(attrs={'class': "form-control"}))
    comments = forms.CharField(label='Comments',widget=forms.TextInput(attrs={'class': "form-control"}))

class SearchlibForm(forms.Form):
    class Meta:
        fields = ['title','author']
    title = forms.CharField(label='Title',max_length=100)
    author = forms.CharField(label='Author')

class LoginForm(forms.Form):
    class Meta:
        fields = ['username','password']

    username = forms.CharField(label='Username')
    password = forms.CharField(widget=forms.PasswordInput())


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['fname','lname','username','password','email']

    fname = forms.CharField(label='First Name')
    lname = forms.CharField(label='Last Name')
    username = forms.CharField(label='Username')
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(label='Email')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['picture']

libapp/views.py
from django.shortcuts import render
import pprint
import random
# Create your views here.
from django.http import HttpResponse,Http404,HttpResponseRedirect
from libapp.models import Book, Dvd, LibUser, Libitem,Suggestion,User,UserProfile
from libapp.forms import SuggestionForm,SearchlibForm,LoginForm,RegisterForm,UserProfileForm
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from libapp.validators import validate_pubyr


# Create your views here.
def index(request):
    # booklist = Book.objects.all() [:10]
    # dvdlist = Dvd.objects.all() [:5]
    # response = HttpResponse()
    # heading1 = '<p>' + 'List of books: ' + '</p>'
    # response.write(heading1)
    # for book in booklist:
    #     para = '<p>' + str(book) + '</p>'
    #     response.write(para)
    # heading2 = '<p>' + 'List of DVDs: ' + '</p>'
    # response.write(heading2)
    # sort = Dvd.objects.order_by('-pubyr')
    # for dvd in sort:
    #     para = '<p>' + str(dvd) + '</p>'
    #
    #     response.write(para)
    #
    # return response

    itemlist = Libitem.objects.all().order_by('title')[:10]

    return render(request, 'libapp/index.html', {'itemlist': itemlist,'name':request.user})

def about(request):
    visit = int(request.COOKIES.get('num','0'))
    visit = visit +1
    limit = 300
    response = render(request,'libapp/about.html',{'visit':visit})
    response.set_cookie('num',visit,max_age=limit)
    return response

def detail(request,item_id):

    # booklist = Book.objects.all()
    # dvdlist = Dvd.objects.all()
    # response = HttpResponse()
    # heading1 = '<p>' + 'List of Books/Dvd\'s' + '</p>'
    # response.write(heading1)
    # isBook = 0
    # isDvd = 0
    #
    # for book in booklist:
    #     # response.write(book.id)
    #     # response.write(item_id)
    #     if book.id == int(item_id):
    #         para = '<p>' + str(book.title)+' '+str(book.author)+' '+str(book.duedate)+' '+str(book.itemtype)+ '</p>'
    #         response.write(para)
    #         isBook = 1
    #         break
    #     else:
    #         isBook = 0
    #
    #
    #
    # for dvd in dvdlist:
    #     # response.write(isBook)
    #     if dvd.id == int(item_id):
    #         para = '<p>' + str(dvd.title)+' '+str(dvd.maker)+' '+str(dvd.duedate)+' '+str(dvd.itemtype)+ '</p>'
    #         response.write(para)
    #         isDvd = 1
    #         break
    #     else:
    #         isDvd = 0
    #
    # if(isBook == 0 and isDvd == 0):
    #     raise Http404
    booklist = Book.objects.all()
    dvdlist = Dvd.objects.all()
    itemlist = Libitem.objects.all()

    return render(request,'libapp/detail.html',{'item_id':item_id,'booklist':booklist,'dvdlist':dvdlist,'itemlist':itemlist})

def suggestions(request):
    suggestionlist = Suggestion.objects.all()
    return render(request, 'libapp/suggestions.html', {'itemlist': suggestionlist})

def newitem(request):
    suggestions = Suggestion.objects.all()
    if request.method == 'POST':
        form = SuggestionForm(request.POST)

        if form.is_valid():
            pubyr = request.POST.get("pubyr")
            validate_pubyr(int(pubyr))
            suggestion = form.save(commit=False)
            suggestion.num_interested = 1
            suggestion.save()
            return HttpResponseRedirect(reverse('libapp:suggestions'))
        else:
            return render(request, 'libapp/newitem.html', {'form':form, 'suggestions':suggestions})
    else:
        form = SuggestionForm()
        return render(request, 'libapp/newitem.html', {'form':form, 'suggestions':suggestions})

def searchlib(request):

        form = SearchlibForm()
        if request.method == 'GET':
            return render(request, 'libapp/search.html', {'form': form})

        else:
            form = SearchlibForm()
            if request.POST.get("title") != '':
                q = request.POST.get("title")
                booklist = Book.objects.filter(title__contains=q)
                dvdlist = Dvd.objects.filter(title__contains=q)
                if request.POST.get("author") != '':
                    r = request.POST.get("author")
                    booklist = booklist.filter(author__contains=r)
                    dvdlist = dvdlist.filter(maker__contains=r)
                return render(request,'libapp/search.html',{'booklist':booklist,'dvdlist':dvdlist,'form':form})
            elif request.POST.get("author") != '':
                q = request.POST.get("author")
                booklist = Book.objects.filter(author__contains=q)
                dvdlist = Dvd.objects.filter(maker__contains=q)
                return render(request, 'libapp/search.html', {'booklist': booklist, 'dvdlist': dvdlist,'form':form})
            else:
                return render(request, 'libapp/search.html',{'form': form})




def user_login(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                luck_num = random.randint(1, 9)
                request.session['luckynum'] = luck_num
                request.session.set_expiry(3600)
                return HttpResponseRedirect(reverse('libapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            form = LoginForm()

            return HttpResponseRedirect(reverse('libapp:login'),'Invalid Login Details')
    else:
        form = LoginForm()

        return render(request, 'libapp/login.html',{'form':form})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('libapp:index')))


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        profile_form = UserProfileForm(request.POST,request.FILES)
        if form.is_valid() and profile_form.is_valid():
            user = User.objects.create_user(request.POST.get("username"),request.POST.get("email"),request.POST.get("password"))
            user.first_name = request.POST.get("fname")
            user.last_name = request.POST.get("lname")
            user.save()

<<<<<<< HEAD
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
=======
>>>>>>> 239430217a857472dac71278789be7b15a676cfe
            return HttpResponseRedirect(reverse(('libapp:login')))
        else:
            return render(request, 'libapp/register.html', {'form': form})
    else:
        form = RegisterForm()
        profile_form = UserProfileForm()
        return render(request, 'libapp/register.html', {'form': form,'profile_form':profile_form})


def myitems(request):
    if request.user.is_authenticated():
        checked_out = Libitem.objects.filter(checked_out=1).filter(user=request.user)
        return render(request,'libapp/myitems.html',{'checked_out':checked_out})
    else:
        return HttpResponse('You are not a LibUser')

def info(request,item_id):
    suggestionlist = Suggestion.objects.all()
    return render(request,'libapp/info.html',{'suggestionlist':suggestionlist,'item_id':item_id})

libapp/templates/libapp/about.html
{% extends 'libapp/base.html' %}
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About | SKAP Library</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Assistant" rel="stylesheet">
    <script src="https://use.fontawesome.com/e574078331.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'libapp/style.css' %}" />
</head>
<body>

{% block body_block %}
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h2>
                    SKAP Library is a place that contains collection of Books and DVD's that the folks can rent out. We offer premier services to all and always take care of our customers to the fullest. We always make sure that we provide the best we can and has been rated positively by most of the community using our services.
                </h2>
            </div>
        </div>
        <div class="navbar navbar-fixed-bottom">
        <div class="container-fluid">
            <div class="row text-center">
                <p style="padding-top: 10px;">Page visited {{ visit }} times.</p>
            </div>
        </div>
        </div>
{% endblock %}
</body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</html>

libapp/templates/libapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>

    <title>SKAP Library</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Assistant" rel="stylesheet">
    <script src="https://use.fontawesome.com/e574078331.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'libapp/style.css' %}" />


</head>

<body>
<<<<<<< HEAD

<nav class="navbar navbar-default">

    <div class="container-fluid">

      <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href = "{% url 'libapp:index' %}">SKAP Library</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'libapp:about' %}">About</a></li>
          {% if request.user.is_authenticated %}
            <li><a href="{% url 'libapp:suggestions' %}">Suggestions</a></li>
            <li><a href="{% url 'libapp:search' %}">Search</a></li>
            <li><a href="{% url 'libapp:newitem' %}">Add item</a></li>
          {% endif %}
      </ul>

        <ul class="nav navbar-nav navbar-right">

            {% if request.user.is_authenticated %}

                <li><a href="{% url 'libapp:myitems' %}">{{ request.user.first_name }}&apos;s Items</a></li>
                <li><a href="javascript:void(0)">{{ request.user.first_name }}&apos;s Lucky Number : {{ request.session.luckynum }}</a></li>
                <li><a href="{% url 'libapp:logout' %}">Logout</a></li>

            {% else %}
                <li><a href="{% url 'libapp:login' %}">Login</a></li>
                <li><a href="javascript:void(0)">Guest&apos;s Lucky Number: 0</a></li>
                <li><a href="{% url 'libapp:register' %}">Register</a></li>
            {% endif %}

        </ul>

    </div><!-- /.navbar-collapse -->

    </div><!-- /.container-fluid -->

</nav>

<div>
    {% block body_block %}*** {% endblock %}
=======
{% if request.user.is_authenticated %}
<div class="now">
    <a class="logout" href="{% url 'libapp:logout' %}">Logout</a>
    <a class="myitems" href="{% url 'libapp:myitems' %}">MyItems</a>
</div>
{% else %}
<div class="now">
    <a class="login" href="{% url 'libapp:login' %}">Login</a>
    <a class="register" href="{% url 'libapp:register' %}">Register</a>
</div>
{% endif %}
<div>
<h1>{% block myhdg %}Hello {{ request.user.first_name }} {% endblock %}</h1>
            {% block body_block %}*** {% endblock %}
>>>>>>> 239430217a857472dac71278789be7b15a676cfe
</div>

</body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</html>

libapp/templates/libapp/index.html
{% extends 'libapp/base.html' %}

{% block body_block %}

    <div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <h1 class="text-center"><span class="index_heading">List of Library items</span></h1>
        </div>
    </div>
    </div>


    {% if itemlist %}

        <div class="col-md-12">

                <div class="col-md-4 col-md-offset-3">
                    <h1><i class="fa fa-book text-center" aria-hidden="true"></i></h1>
                    {% for item in itemlist %}
                        {% if item.itemtype == "Book" %}
                            <h4 style="padding-top: 3%"><a href="{% url 'libapp:detail' item.id %}">{{ item.title}}</a></h4>
                        {% endif %}
                    {% endfor %}
                </div>

                <div class="col-md-4">
                    <h1><i class="glyphicon glyphicon-cd text-center" aria-hidden="true"></i></h1>
                    {% for item in itemlist %}
                    {% if item.itemtype == "DVD" %}
                        <h4 style="padding-top: 3%"><a href="{% url 'libapp:detail' item.id %}">{{ item.title}}</a></h4>
                    {% endif %}
                    {% endfor %}
                </div>


        </div>
    {% else %}
        <strong>There are no available items!</strong>
    {% endif %}

{% endblock %}

libapp/templates/libapp/newitem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Item</title>
</head>
<body>
{% extends 'libapp/base.html' %}
{% block body_block %}

    <form class="form-horizontal" action="{% url 'libapp:newitem' %}" method="post">

        <div class="form-group">
            <label for="id_title" class="col-sm-2 control-label">Title:</label>
        <div class="col-sm-8">
          {{ form.title }}
            <div>


            <span class="alert alert-error">
            {% if form.errors %}
    {% for field in form %}
            {% if field.name == 'title' %}
                {{ field.errors }}
                {% endif %}
            {% endfor %}

                 {% endif %}
            </span>


            </div>
        </div>

      </div>
        <div class="form-group">
            <label for="id_pubyr" class="col-sm-2 control-label">Publication Year:</label>
        <div class="col-sm-8">
          {{ form.pubyr }}

            <span class="alert alert-error">
            {% if form.errors %}
    {% for field in form %}
            {% if field.name == 'pubyr' %}
                {{ field.errors }}
                {% endif %}
            {% endfor %}

                 {% endif %}
            </span>
        </div>
      </div>
         <div class="form-group">
            <label for="id_type" class="col-sm-2 control-label">Type:</label>
        <div class="col-sm-8">
          {{ form.type }}

            <span class="alert alert-error">
            {% if form.errors %}
    {% for field in form %}
            {% if field.name == 'type' %}
                {{ field.errors }}
                {% endif %}
            {% endfor %}

                 {% endif %}
            </span>
        </div>
      </div>
         <div class="form-group">
            <label for="id_cost" class="col-sm-2 control-label">Cost:</label>
        <div class="col-sm-8">
          {{ form.cost }}

            <span class="alert alert-error">
            {% if form.errors %}
    {% for field in form %}
            {% if field.name == 'cost' %}
                {{ field.errors }}
                {% endif %}
            {% endfor %}

                 {% endif %}
            </span>
        </div>
      </div>
         <div class="form-group">
            <label for="id_comments" class="col-sm-2 control-label">Comments:</label>
        <div class="col-sm-8">
          {{ form.comments }}

            <span class="alert alert-error">
            {% if form.errors %}
    {% for field in form %}
            {% if field.name == 'comments' %}
                {{ field.errors }}
                {% endif %}
            {% endfor %}

                 {% endif %}
            </span>
        </div>
      </div>
<div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                <button type="submit" class="btn btn-primary">Create</button>
                {% csrf_token %}
            </div>
        </div>
</form>
{% endblock %}
</body>
</html>

libapp/templates/libapp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register | SKAP Library</title>
</head>
<body>
{% extends 'libapp/base.html' %}
{% block body_block %}
<<<<<<< HEAD

    <form class="form-horizontal" action="{% url 'libapp:register' %}" method="post">

        <div class="form-group">
            <label for="first_name" class="col-sm-2 control-label">First Name:</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" name="fname">
            </div>
        </div>

        <div class="form-group">
            <label for="last_name" class="col-sm-2 control-label">Last Name:</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" name="lname">
            </div>
        </div>

        <div class="form-group">
            <label for="username" class="col-sm-2 control-label">Username:</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" name="username">
            </div>
        </div>

        <div class="form-group">
            <label for="email" class="col-sm-2 control-label">Email:</label>
            <div class="col-sm-8">
              <input type="email" class="form-control" name="email">
            </div>
        </div>

        <div class="form-group">
            <label for="password" class="col-sm-2 control-label">Password:</label>
            <div class="col-sm-8">
              <input type="password" class="form-control" name="password">
            </div>
        </div>
         <div class="form-group">
             <label for="id_picture" class="col-sm-2 control-label"></label>
            <div class="col-sm-8">
            {{ profile_form }}
                </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                <button type="submit" class="btn btn-primary">Register</button>
                {% csrf_token %}
            </div>
        </div>


    </form>

=======
<form action="{% url 'libapp:register' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ upload }}
        <input type="submit" value="Register">
</form>
>>>>>>> 239430217a857472dac71278789be7b15a676cfe
{% endblock %}
</body>
</html>

libapp/templates/libapp/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
</head>
<body>
{% extends 'libapp/base.html' %}

{% block body_block %}

    <div class="container">
    <div class="row padding-3">
        <div class="col-md-12 text-center">
            <span class="index_heading">Search</span>
        </div>
    </div>


    <form class="form-horizontal" action="{% url 'libapp:search' %}" method="post">
      <div class="form-group">
        <label for="title" class="col-sm-2 control-label">Title:</label>
        <div class="col-sm-8">
          <input type="text" id="title" class="form-control" name="title" placeholder="Search by Title">
        </div>
      </div>
      <div class="form-group">
        <label for="author" class="col-sm-2 control-label">Author:</label>
        <div class="col-sm-8">
          <input type="text" id="author" class="form-control" name="author" placeholder="Search by Author">
        </div>
      </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                <button type="submit" class="btn btn-default">Search</button>
                {% csrf_token %}
            </div>
        </div>
</form>
</div>

    {% if booklist %}
        <div class="container">
        <div class="row">
                <h1 class="text-center"><span class="index_heading">Results</span></h1>
        </div>


        <div class="row">
            {% for result in booklist %}
                <div class="col-md-12">
                <div class="col-md-2 col-md-offset-3">
                    <h1><i class="fa fa-book" aria-hidden="true"></i></h1>
                </div>
                <div class="col-md-6">
                    <h4 style="padding-top: 20px">Title: {{ result.title }} | Author: {{ result.author }}</h4>
                    <h4>Publication Year: {{ result.pubyr }} | Due date: {{ result.duedate }}</h4>
                </div>
                </div>
            {% endfor %}
         </div>
        </div>
    {% endif %}


    {% if dvdlist %}
        <div class="container">
        <div class="row">
            <h1 class="text-center"><span class="index_heading">Results</span></h1>
        </div>

         <div class="row">
            {% for result in dvdlist %}
                <div class="col-md-2 col-md-offset-3">
                    <h1><i class="glyphicon glyphicon-cd" aria-hidden="true"></i></h1>
                </div>
                <div class="col-md-6">
                    <h2>Title: {{ result.title }} | Maker: {{ result.maker }}</h2>
                </div>
            {% endfor %}
         </div>
        </div>
    {% endif %}
{% endblock %}

</form>
</body>
</html>